site_name: Platform-Aux-LiveCasino
site_description: LiveCasino data processor
nav:
  - Home: index.md
  - Architecture:
      - Modules: modules/index.md
      - Flow: modules/flows.md
      - Events: modules/kafkaevents.md
      - API: modules/api.md
      - Testing: modules/testing.md

plugins:
  - techdocs-core